services:
  pg-1:
    image: timescale/timescaledb:latest-pg16
    container_name: nfl-analytics-pg-1
    environment:
      - POSTGRES_USER=dro
      - POSTGRES_PASSWORD=sicillionbillions
      - POSTGRES_DB=devdb01
    ports:
      - "5544:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dro -d devdb01"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - nfl-analytics

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=nfl-analytics-pg-1
      - DB_PORT=5432
      - DB_NAME=devdb01
      - DB_USER=dro
      - DB_PASSWORD=sicillionbillions
    restart: unless-stopped
    networks:
      - nfl-analytics
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8501/_stcore/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pgdata:
    name: nfl-analytics-pgdata

networks:
  nfl-analytics:
    external: true
