name: Nightly Data Quality

on:
  schedule:
    - cron: '0 6 * * *'  # 6am UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  schema-validation:
    name: Database Schema Validation
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: timescale/timescaledb:latest-pg16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Apply schema migrations
        env:
          PGPASSWORD: testpass
        run: |
          psql -h localhost -p 5432 -U testuser -d testdb -f db/001_init.sql
          psql -h localhost -p 5432 -U testuser -d testdb -f db/002_timescale.sql
      
      - name: Verify schema exists
        env:
          PGPASSWORD: testpass
        run: |
          psql -h localhost -p 5432 -U testuser -d testdb -f db/verify_schema.sql
      
      - name: Run SQL data quality tests
        env:
          PGPASSWORD: testpass
        run: |
          # Check if test SQL files exist, if so run them
          if [ -f tests/sql/test_schema.sql ]; then
            psql -h localhost -p 5432 -U testuser -d testdb -f tests/sql/test_schema.sql
          fi
          if [ -f tests/sql/test_data_quality.sql ]; then
            psql -h localhost -p 5432 -U testuser -d testdb -f tests/sql/test_data_quality.sql
          fi
      
      - name: Report to GitHub
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Nightly Data Quality Check Failed',
              body: `The nightly data quality check failed on ${new Date().toISOString()}\n\n` +
                    `**Run**: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\n\n` +
                    `Please investigate the schema or data quality issues.`,
              labels: ['automated', 'data-quality', 'ci-failure']
            })

  notebook-validation:
    name: Validate Quarto Notebooks
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Check notebook syntax
        run: |
          # Check if notebooks exist and validate syntax
          for notebook in notebooks/*.qmd; do
            if [ -f "$notebook" ]; then
              echo "Validating $notebook"
              quarto check "$notebook" || echo "Warning: $notebook has issues"
            fi
          done
        continue-on-error: true
